### ISSUE TITLE
Permissions: why these differences? (fdroid vs app info)

### ISSUE THREAD

**Issue by serrq** [Kin69/EasyNotes#107]
![1000115813](https://github.com/user-attachments/assets/5fa27f75-e723-4141-ae5e-12c85595516d)

![1000115815](https://github.com/user-attachments/assets/68be0116-93d6-4d01-847e-58fed76df69e)

**Comment by Kin69** [comment]
Android doesn't show detailed permissions like F-Droid, but I didn't declare that my app should use any permissions. When I installed the app to observe these permissions, I discovered that all other FOSS apps on my phone also use these permissions. This leads me to believe that it’s probably the default Android receiver (which I did declare) that is using these permissions. Therefore, I think these are default permissions for widget functionality.

The "view network" permission is not the same as network connection; it only checks if your device is connected to a network, which I think is useless since it doesn't have actual network access permission.

If you want to make sure that the app doesn't require any permissions on its own, you can check the AndroidManifest.xml file of the app [here](https://github.com/Kin69/EasyNotes/blob/master/app/src/main/AndroidManifest.xml). For example, if I wanted to have internet access, I would need to include <uses-permission android:name="android.permission.INTERNET" />, which I don't. There are no permissions declared in the manifest.

**Comment by Kin69** [comment]
OpenCalc does not need to use a those permissions because it does not have a widget. If a widget were implemented, it would require those permissions.

**Comment by Kin69** [comment]
@serrq I found a way to remove permissions from my app, and the widget still works perfectly without them. I will attempt to release version 1.3.5 without any permissions. If there are no issues with the widget's functionality, I'll keep it permission-free.
