### ISSUE TITLE
Edit directly when clicking widget 

### ISSUE THREAD

**Issue by AderynCrow** [Kin69/EasyNotes#108]
Instantly going into edit mode when opening a note from the widget would make quick edits much faster and convenient, which would be invaluable for highly dynamic notes like a to-do list or scratchpad.
The widget itself already offers a rendered preview of the markdown, so opening to the preview shouldn't be necessary.

I would prefer it to be the default since I believe it to be expected behaviour since other similar apps behave that way as well, but because opening notes from within the app also opens the preview first, it could create confusion since the behaviour would change based on where a note was opened from.
Mayhaps a toggle "edit directly from widget" could help with that problem.

**Comment by Kin69** [comment]
Thanks for the suggestion! I've implemented the feature so that opening a note from the widget now takes you directly into edit mode. You can try it out in the latest nightly build: Nightly Easy Notes.

I decided not to add a specific setting for this, as the scrollable widget should function similarly to the preview. However, if you have any further feedback or if there's anything else you'd like to see, just let me know!
