### ISSUE TITLE
Permissions and Privacy Information

### ISSUE THREAD

**Issue by issuant** [Kin69/EasyNotes#111]
A note app that does not arbitrarily call out to the internet has been hard to find and there is no information about the permissions EasyNotes utilizes (internet for example) or their privacy implications.

**Comment by Kin69** [comment]
First of all, the app doesn't require internet permission; it requires ACCESS_NETWORK_STATE, which allows it to check if the network is connected. These permissions are added by a third-party library, Glance (widget), which for some reason needs them. I will try to block the ACCESS_NETWORK_STATE permission in the app manifest, but other permissions may be necessary for the widget's functionality. Additionally, Glance isn't just a random library from the internet; it's an official Android library for creating widgets. I will also create a Privacy Policy in the README.md file.

**Comment by Kin69** [comment]
So you are looking for a Privacy Policy similar to this example from [GitHub](https://github.com/hushenghao/AndroidEasterEggs/wiki/Privacy-policy)?

**Comment by derei** [comment]
@issuant 

To answer your question:
![EasyNote_Permissions](https://github.com/user-attachments/assets/e48378f1-35fd-40ef-8859-0c04c5aa2b29)

(if you have any questions regarding the permissions, let's say, if you are unable to find documentation and explanation for them - which I strongly doubt, anyway - please ask here and I'll be happy to provide clarifications).

**Comment by derei** [comment]
@issuant 

The permission is added to the app automatically and is meant as a security measure against unprotected broadcasts. In my understanding, what this specific permission does, is preventing the registered broadcast receiver to be visible to other apps. Which is a good thing 😜

https://stackoverflow.com/questions/74146297/android-adding-dynamic-receiver-not-exported-permission-in-release-build

Now, regarding sensors permission, that permission has been introduced with Android 11 and it manages sensors such as environmental (temp, pressure, humid.), proximity, motion, etc.
Whilst I can't tell 100% why the app needs it, it could potentially be for preventing accidental touches when editing a note. Perhaps @Kin69 can clarify this.

Overall, the app doesn't send anything out, because it has no internet access permission, no call or sms permission, so it has no means to send data out.
I disabled the sensor permission in app settings and there was no visible consequence. It's very

**Comment by derei** [comment]
@issuant 

The app I used in this case is Permission Pilot https://apt.izzysoft.de/fdroid/index/apk/eu.darken.myperm

But you could also use Exodus https://f-droid.org/packages/org.eu.exodus_privacy.exodusprivacy/

**Comment by Kin69** [comment]
In the latest update, the permissions that were previously added by the widget plugin have been removed, as they are no needed. It appears this might be a bug on the module’s side.
