### ISSUE TITLE
[bug] undefined note text

### ISSUE THREAD

**Issue by dxrknesss** [Kin69/EasyNotes#19]
When I leave the mote without adiing any text, it literally changes it to "undefined"

pls fix it to just leave the note empty

**Comment by Kin69** [comment]
Hey there, I've looked into the problem you mentioned with the note saving, and I've made the necessary adjustments. Now, when you leave the note empty, it stay empty instead of changing to "undefined".

![issue19](https://github.com/Kin69/EasyNotes/assets/109698804/f4ca4997-a6f7-4ed7-b990-a2e8c4c3dcb5)

If you run into any more issues, just let me know!
