### ISSUE TITLE
version1.2，too much bug

### ISSUE THREAD

**Issue by james0336** [Kin69/EasyNotes#23]
the tool butons on the editing  have disappeared

**Comment by Kin69** [comment]
@james0336 You should see toolbar when editing description. 

If  not could you please send screenshots?

**Comment by wadeack** [comment]
@james0336 , can you please specify the Android version? 

From what I can observe on Android 14 (Samsung galaxy tab) the markdown toolbar works fine but on Android 9 (Umidigi x) it feels broken because keyboard could not be detected in edit mode and so it's always hidden.
Here how it looks like for me on Android 14:
![image](https://github.com/Kin69/EasyNotes/assets/40576661/022bb5cd-3266-4bad-a635-7f0a1da00de0)
and on Android 9:
![image](https://github.com/Kin69/EasyNotes/assets/40576661/e0f3ec25-f405-4e5b-83d1-18efa0b245ec)

I've tried fixing it in my fork, but it seems there are more bugs to be caught.

**Comment by Kin69** [comment]
@wadeack I was thinking about using FocusManager. When the textfield is focused, it could just make the bottom padding smaller.

Let me know if you want to implement this and create a pull request, or if I should fix it.

Also, thanks for your contribution.

**Comment by wadeack** [comment]
Hi @Kin69 , yes, I'd like to investigate it and will create a PR once I have something. Thank you!
