### ISSUE TITLE
Material You Dynamic Theme does not work

### ISSUE THREAD

**Issue by PhilippKosarev** [Kin69/EasyNotes#26]
With Material You theme enabled the app uses the default blue accents instead.

Android version: 14
OneUI version: 6.0
App version: 1.2

Thank you for the app by the way; it's the best simple note taking app I've tried so far.

**Comment by Kin69** [comment]
Hi there,

Thanks for your feedback! I'm glad to hear you're enjoying the app.

Regarding the issue with the Material You theme showing default blue accents instead of adapting to the theme, could you please provide a bit more information to help me diagnose the problem? Specifically, it would be helpful if you could:

  1. When material theme is disabled is it showing brown scheme and when enabled blue scheme?
  2. Could you share some screenshots showing the issue.
  3. Ideally, provide a logcat log to capture any potential errors or warnings that might be related to this behavior.

**Comment by PhilippKosarev** [comment]
Hey,

1. Yes, I can see the beautiful coffee theme :)
2. Not quite a screenshot, but here is a comparison of Easy Notes' dynamic theme theme with Aniyomi https://github.com/Kin69/EasyNotes/assets/102914158/44de6201-f701-4f55-8bd3-c93d56ff3f68
3. I'm not very familiar with LogFox so if the logs look incorrect please tell me. [EasyNotes.log](https://github.com/user-attachments/files/15570622/EasyNotes.log)

**Comment by PhilippKosarev** [comment]
Since this is an issue with OneUI and not the app itself I'll be closing this issue.
It's been discussed further [here](https://github.com/Malopieds/InnerTune/issues/256).
