### ISSUE TITLE
Apply radius to the items under information

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [Kin69/EasyNotes#74]
I found that the general radius was to much to my personal taste, so I was glad to see this customizable with the new release.
However, it doesn't apply to the items like _creation date, number of words, ..._ which are under the information of a note. This feels inconsistent.

**Comment by Kin69** [comment]
Thanks for your feedback. The issue with the radius customization not applying to certain elements should be fixed in the latest nightly build of EasyNotes, which you can download [here](https://github.com/Kin69/EasyNotes/releases/download/Nightly/EasyNotes-nightly.apk). If you still encounter the problem, please feel free to reopen the issue.

Thanks for feedback!
